#! /bin/bash
irsend --device=/var/run/lirc/lircd1 SEND_ONCE samsung630 source
sleep .2
irsend --device=/var/run/lirc/lircd1 SEND_ONCE samsung630 up
sleep .2
irsend --device=/var/run/lirc/lircd1 SEND_ONCE samsung630 middle
